# Site Settings
title: Alison Américo
email: alison.americo@gmail.com
description: Some text about your blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alisonamerico.github.io/"
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Alison Américo
user_description: Se preocupe menos em provar que é bom e mais em aprender algo novo.
  Seja hoje melhor do que você foi ontem.
disqus_username: alisonamerico

# Social Media
# Remove the item if you don't need it
github_username: alisonamerico
twitter_username: alisonamerico
linkedin_username: alisonamerico

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
